# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

dropbox_token: LpGdPkte5BsAAAAAAAAAATfM9_VyJUFF79fBMp2iAuBywkTLSrVw3zh6Qr3Y1o-7

zendesk_email: louisfelix95@hotmail.com

zendesk_token: fjTUb7syodwPpgWxxHW3UFKwpUcIPksIHEIoumyO

TWILIO_ACCOUNT_SID: ACab428b7e54e6aa4f3ffd74b2b92d5f08

TWILIO_AUTH_TOKEN: 3dd8a31b56f9ff6cd5e61be216546a99

RECIPIENT_PHONE_NUMBER: '+18198171295'

dropbox_key: szbhdmwiygul1c1

dropbox_secret: tr9nc7ttdhh9oqv